### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by moul**
Some small fixes

### CODE REVIEW

**Comment by moul** [comment]
For me, the image is ok, I will prepare a release tomorrow and tell you here

I have small improvements ideas, I will create issues on GitHub so you or someone else can manage to improve the image later

:+1:

**Comment by onli** [comment]
:+1:

**Comment by moul** [comment]
Here is the public image: http://cloud.scaleway.com/#/servers/new?image=39459634-e450-42b6-a352-5aabcaca396f

We will update the image hub soon :)

**Comment by edouardb** [comment]
:+1:

**Comment by onli** [comment]
Can you ping me again when the image hub is updated? I'd like to write about that.

**Comment by moul** [comment]
Yes sure, @edouardb, it's for you :)

**Comment by edouardb** [comment]
Woot https://hub.scaleway.com/serendipity.html

Logo will be fixed asap.

**Comment by onli** [comment]
Great, thanks! We will probably blog as a project about this in a few days.

**Pull request merged**
